apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secret
  namespace: brainx
type: Opaque
stringData:
  JWT_SECRET: CHANGE_ME
  MAIL_USERNAME: CHANGE_ME
  MAIL_PASSWORD: CHANGE_ME
  SEED_ADMIN_LOGIN_ID: CHANGE_ME
  SEED_ADMIN_PASSWORD: CHANGE_ME
  SEED_ADMIN_NAME: CHANGE_ME
